
BASE62= "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
def id_to_base(id:int):
    """
    Convert an integer id to a base 62 string.

    The base 62 string is generated by taking the remainder of the id
    divided by 62, and appending the corresponding character from the
    BASE62 string. This is repeated until the id is 0.

    Args:
        id (int): The integer id to be converted.

    Returns:
        str: The base 62 string representation of the id.
    """
    if id == 0:
        return BASE62[0]
    result=[]
    while id > 0:
        result.append(BASE62[id%62])
        id//=62
    return ''.join(reversed(result))